# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Starter
version:      1.40
version_from: lib/Module/Starter.pm
installdirs:  site
requires:
    ExtUtils::Command:             0
    File::Spec:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
