--- #YAML:1.0
name:               Module-Starter
version:            1.54_01
abstract:           a simple starter kit for any module
author:
    - Andy Lester <andy@petdance.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::Command:  0
    File::Spec:         0
    Getopt::Long:       0
    Pod::Usage:         1.21
    Test::Harness:      0.21
    Test::More:         0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Starter
    homepage:    http://code.google.com/p/module-starter/
    repository:  http://module-starter.googlecode.com/svn/trunk/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
