--- #YAML:1.0
name:                Module-Starter
version:             1.50
abstract:            a simple starter kit for any module
license:             perl
author:              
    - Andy Lester <andy@petdance.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    ExtUtils::Command:             0
    File::Spec:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Test::More:                    0
    Test::Pod:                     1.22
    Test::Pod::Coverage:           1.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
