---
abstract: 'a simple starter kit for any module'
author:
  - 'Andy Lester <andy@petdance.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Starter
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::Command: 0
  File::Spec: 0
  Getopt::Long: 0
  Path::Class: 0
  Pod::Usage: 1.21
  Test::Harness: 0.21
  Test::More: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Starter
  homepage: https://github.com/xsawyerx/module-starter
  repository: https://github.com/xsawyerx/module-starter.git
version: 1.58_03
