--- #YAML:1.0
name:                Module-Starter
version:             1.43_01
abstract:            a simple starter kit for any module
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    ExtUtils::Command:             0
    File::Spec:                    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andy Lester <andy@petdance.com>
